[FileDialog]
history=file:///home/aurevelle/.config/qutebrowser, file:///home/aurevelle/valley of riches/My Presentations/scienceIsabelle/OrganSystems, file:///home/aurevelle/Downloads, file:///home/aurevelle/Pictures/Screenshots
lastVisited=file:///home/aurevelle/Downloads
qtVersion=6.9.1
shortcuts=file:, file:///home/aurevelle
sidebarWidth=89
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xeb\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\b\0\0\0\x1\0\0\0\0\0\0\0;\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0h\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
